### ISSUE TITLE
Adapt the Delphi Management to new API

### ISSUE THREAD

**Issue by Ayybeeshafi** [delphi-hub/delphi-management#113]
In order to effectively communicate with the Instance Registry there is a need to change the API routes at Management end.

**Comment by Ayybeeshafi** [comment]
Hi @janniclas 
Adding a component is working fine.
Number of running instances is also being displayed.
network() is working fine.

The status of instance on UI doesnot changes to "deployed" even when in Instance registry log says "Deployed new WebApi container with docker id: ... "
Hence, play, pause buttons on the UI are greyed out and I am unable to test handlerequest().

What can be the cause of this issue? Any leads

**Comment by janniclas** [comment]
I can confirm your finding regarding the not changing status. I did a little digging and noticed that the instance registry doesn't send an event regarding a new instance state. The instance's state, when retrieved by a query via the /instances/network endpoint, is also deploying, even though the instance is running. For me this looks like an missing update of the internal state in the ir?

attached are some screenshots from the management server logs showing the result of the instances/network request, the logs of the instance registry, a screenshot of the running docker containers, and an excerpt of the docker network inspect call. Maybe this helps you to pinpoint our problem @johannesduesing 
<img width="1383" alt="screen shot 2019-02-10 at 21 33 49" src="https://user-images.githubusercontent.com/8062521/52539242-231fec00-2d7c-11e9-91a0-aacbdc529d48.png">
<img width="1371" alt="screen shot 2019-02-10 at 21 33 30" src="https://user-images.githubusercontent.com/8062521/52539245-26b37300-2d7c-11e9-9bb5-8543db21c989.png">
<img width="1371" alt="screen shot 2019-02-10 at 21 33 19" src="https://user-images.githubusercontent.com/8062521/52539246-2adf9080-2d7c-11e9-81e7-872da20891f8.png">

<img width="905" alt="screen shot 2019-02-10 at 21 35 02" src="https://user-images.githubusercontent.com/8062521/52539240-1f8c6500-2d7c-11e9-9e6b-517f1970ff1d.png">

**Comment by johannesduesing** [comment]
From the registry logs it seems that the instances, after being deployed, do not connect to the registry to report that they are running. Most likely this is a configuration problem (see config value registryUri), it would be helpful to see the logs of the docker containers.

**Comment by janniclas** [comment]
@Ayybeeshafi I made several changes to the branch and now everything is working fine for me, please verify if it works for you too.
On my end there was the need to configure some default docker settings, because I work in os x, but this shouldn't be necessary for you since you are running linux.

**Comment by Ayybeeshafi** [comment]
@janniclas The actions are still not working for me. I also think it is some configuration problem at my end after the traefik feature. If the code is working fine at your end and is up to the scala code style standards. Feel free to merge it.
