### ISSUE TITLE
Add a section on the front page that shows system information on the running system

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-management#13]
As an authenticated user, I would like to immediately see the context I am currently working in. This means the system name I am logged into, running JVM version, Scala version, CPU load, etc. etc. Think of anything that might help DevOps to run the complete system.

**Comment by bhermann** [comment]
Are you still working on this issue, @Chinmay-92 @ishwaryaPaderborn ?

**Comment by ishwaryaPaderborn** [comment]
Yes, we are working on it. We will get back to you if we have any doubts.

**Comment by bhermann** [comment]
Great! :smile:

**Comment by bhermann** [comment]
Closed by #34
