### ISSUE TITLE
Integrate Angular for Scala Play

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-management#17]
Integrate angular as decided in #8 .

**Comment by bhermann** [comment]
Here is the link we discussed: https://github.com/yohangz/scala-play-angular-seed

**Comment by bhermann** [comment]
Just in delphi-management please. Thank you!

**Comment by bhermann** [comment]
Thanks for letting me know. Looking forward to this.

**Comment by janniclas** [comment]
quick update. the feature branch now serves a dummy version of the angular dashboard framwork we plan to use for a first version. 

Before creating a pull request to the develop branch the basic information about delphi have to be integrated and some more dummy data has to be removed from the dashboard.

**Comment by janniclas** [comment]
Remaining tasks until integration in develop branch:

- [ ] research how the authentication framework silhouette can be integrated with angular + scala play
- [ ] remove boilerplate code from the dashboard framework template
- [ ] move previously available information about delphi to the new angular app

**Comment by bhermann** [comment]
Closed with #70 .
