### ISSUE TITLE
Increase the size of the text next to the Delphi logo on the top left corner of the page.

### ISSUE THREAD

**Issue by 24santoshr** [delphi-hub/delphi-management#43]
The text present next to Delphi logo (which is also a hyperlink) at the top left corner of the page is very small. The font size could be increased to make it more clearer.

![delphi_mgmt](https://user-images.githubusercontent.com/32432999/41262003-cdbe75ea-6dde-11e8-92ff-2019c4f57546.png)

**Comment by bhermann** [comment]
This should be technically a logo... currently we use the SVG there. Maybe the world is not ready for vector graphics? Let's try to use the PNG version of the logo instead.

**Comment by bhermann** [comment]
What do you mean by modify? I mean... there is an official logo. :)
![logo 4x](https://user-images.githubusercontent.com/1974799/41424350-13aea41e-6ffe-11e8-9081-b35c11f44fdc.png)

**Comment by 24santoshr** [comment]
Sorry..I meant can I change from vector graphics format to PNG format and give it a try?

**Comment by bhermann** [comment]
Ahhh sorry... Yes of course!

**Comment by janniclas** [comment]
@24santoshr I think this should be revisited. The current version created by pull request https://github.com/delphi-hub/delphi-management/pull/46 causes this behaviour at my machine. 

![image](https://user-images.githubusercontent.com/8062521/41524169-db73a338-72dc-11e8-908f-b3a0bc8c33a9.png)

**Comment by janniclas** [comment]
a short investigation showed that the height attribute was accidentally removed in the notAuthenticated.scala.html file. This should be set to an appropriate value without breaking the initial design.

**Comment by 24santoshr** [comment]
Sorry for that. Yes height attribute has been removed accidentally. I will do the necessary changes now.

**Comment by 24santoshr** [comment]
Closed with PR#48
