### ISSUE TITLE
Ability to start Elasticsearch service instance if not running

### ISSUE THREAD

**Issue by 24santoshr** [delphi-hub/delphi-management#49]
Is your feature request related to a problem? Please describe.
Crawler component may be started without a running instance of Elasticsearch.

Describe the solution you'd like
The current functionality throws an exception as Connection refused when Elasticsearch instance is not running. so when this is the case we can probably alert the User about the issue and run a script automatically to enable/start the Elasticsearch service if they want to use the crawler.

**Comment by bhermann** [comment]
This might be solved with an integration with the already running instance of portainer.

**Comment by bhermann** [comment]
Closed due to redesign
