### ISSUE TITLE
Vulnerable dependencies: play-silhouette 5.0.0 uses outdated dependencies

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-management#55]
**Describe the bug**
The dependency to `play-silhouette 5.0.0` entails dependencies to vulnerable versions of `com.fasterxml.jackson.core:jackson-databind` and `com.fasterxml.jackson.core:jackson-core`

**To Reproduce**
Not necessary. 
See snyk report: https://app.snyk.io/org/delphi-hub/project/d1073126-45d0-4168-9cfd-15e5dc86f5f0

**Expected behavior**
Please update silhouette to it current version (I saw 5.0.5). My initial try resulted in some compilation issues, that might be related of our usage of the library. 

**Screenshots**
No applicable

**Affected components (if known)**
management

**Desktop (please complete the following information, if relevant):**
not applicable

**Smartphone (please complete the following information, if relevant):**
not applicable

**Additional context**
none

**Comment by janniclas** [comment]
This was addressed in commit a9583eb62d5f571dbab6534cfede97bcb50006bc . I will leave this ticket open for now, until the branch was merged at least into the develop branch.

**Comment by janniclas** [comment]
adressed in https://github.com/delphi-hub/delphi-management/pull/70

**Comment by janniclas** [comment]
closing this, since the code fixing this issue made it into develop quite a while ago.
