### ISSUE TITLE
CI: Enable running angular based tests on the build server

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-management#73]
**Is your feature request related to a problem? Please describe.**
It's pretty neat that we now have some tests running on the angular layer of the application. 
It would be much better if those tests were run by the build server on a regular basis to catch regression early. 

**Describe the solution you'd like**
Something that runs these tests on the travis-ci based build server and makes the build fail when the tests fail.

**Describe alternatives you've considered**
We can also use [BrowserStack](https://www.browserstack.com/) if you like that better.

**Additional context**
I just added the angular build part to build automation. So we see when some commit breaks the build of the client application.

**Comment by janniclas** [comment]
this was resolved with the integration of the socket service
