### ISSUE TITLE
Decide on a UI framework

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi-management#8]
We already decided to use Scala Play for delivery. 
However, having a UI framework on top will help user experience.
Please evaluate the following framework:

- Angular
- vue.js
- Nuxt
- React

Create your own categories for the evaluation. 
As a hint: I would like us to be able to do animations that look native, as in: https://css-tricks.com/native-like-animations-for-page-transitions-on-the-web/

**Comment by bhermann** [comment]
Document into the Wiki please.

**Comment by janniclas** [comment]
@bhermann could you provide a short overview of the use case for the web app to enable us to define better fitting categories for the different frameworks.

**Comment by bhermann** [comment]
For the webapp or for the management webapp?

**Comment by janniclas** [comment]
If we want to use the same Frontend framework for both, which would most likely be a good idea, an overview of both would be great, just to gasp an idea of the requirements to the frameworks.

**Comment by bhermann** [comment]
I'll sketch some preliminary thoughts

**webapp**
- search for a set of projects matching a query 
- designing this query (lots of helping UI hopefully)
- drill into the details of projects (possibly with data visualization)
- maybe traverse the dependencies/links of this project (graphically challenging)
- later on some features for registered users

**management**
- an overview over the crawling process (charts, graphs, control (meaning starting, stopping, pausing, resetting), statistics)
- control over the docker containers used (possibly swarmed or something similar)
- some control over the elasticsearch
- a live view on the usage
- usage statistics

**Comment by janniclas** [comment]
we created a wiki entry with an initial comparison of the mentioned frameworks - [UI framework comparison](https://github.com/delphi-hub/delphi-management/wiki/UI-Framework)

**Comment by bhermann** [comment]
Thank you both!
Let's review your finding in tomorrow's meeting and then as a group decide and close this issue afterwards.

**Comment by bhermann** [comment]
The group decided for Angular. Thanks all.
